const express = require('express')
const path = require('path')
const favicon = require('serve-favicon')
const PORT = process.env.PORT || 5052
express()
    .use('/public',express.static(path.join(__dirname, 'public')))
    .use(favicon(__dirname + '/public/favicon.ico'))
    .set('views', path.join(__dirname, 'views'))
    .set('view engine', 'ejs' )
    .get('/', (req, res) => res.render('index'))
    .listen(PORT, () => console.log(`Listening on ${ PORT }`))